# SPDX-License-Identifier: GPL-2.0
rtl8192s-common-objs :=		\
		dm_common.o \
		fw_common.o \
		hw_common.o \
		main.o \
		phy_common.o \
		rf_common.o \
		table_common.o \
		trx_common.o

obj-$(CONFIG_RTL8192S_COMMON) += rtl8192s-common.o
